package com.ecommerce.shop.domain;

import static com.ecommerce.shop.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ShopOrderAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopOrderAllPropertiesEquals(ShopOrder expected, ShopOrder actual) {
        assertShopOrderAutoGeneratedPropertiesEquals(expected, actual);
        assertShopOrderAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopOrderAllUpdatablePropertiesEquals(ShopOrder expected, ShopOrder actual) {
        assertShopOrderUpdatableFieldsEquals(expected, actual);
        assertShopOrderUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopOrderAutoGeneratedPropertiesEquals(ShopOrder expected, ShopOrder actual) {
        assertThat(actual)
            .as("Verify ShopOrder auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopOrderUpdatableFieldsEquals(ShopOrder expected, ShopOrder actual) {
        assertThat(actual)
            .as("Verify ShopOrder relevant properties")
            .satisfies(a -> assertThat(a.getPlacedAt()).as("check placedAt").isEqualTo(expected.getPlacedAt()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a ->
                assertThat(a.getTotalAmount())
                    .as("check totalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShopOrderUpdatableRelationshipsEquals(ShopOrder expected, ShopOrder actual) {
        assertThat(actual)
            .as("Verify ShopOrder relationships")
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
